language: java
script: ant init
sudo: require
deploy:
   edge: true
   provider: cloudfoundry
   username: adityasagar1992@gmail.com
   password: 1992ashu
   api: https://api.run.pivotal.io
   organization: hack
   space: development